<a href="https://colab.research.google.com/github/ayushxx7/Auto-File-Renamer/blob/master/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1Cc2f-g35_V81GwETV_LZ8Ja6u_TQOEtA')

     |████████████████████████████████| 71kB 3.4MB/s 


> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# 5 Powerful PyTorch functions

**Deep learning** is the process of analyzing data and generating relevant models out of it (It is a subset of Machine Learning). We essentially provide a data set to the machine, which then performs some rigorous computations to generate a prediction model. **The prediction model can then be used on a different dataset to (you guessed it) predict the output.** PyTorch is a library that helps us in for deep learning. In essence, the PyTorch library provides us access to a n-dimensional array of `tensors` on which we can perform computations (such as add, subtract, multiply, gradient descent etc.). The multi-dimensional is similary to `numpy` in many ways, however, it is heavily optimized to harness the power of the GPU.

- function 1
- function 2
- function 3
- function 4
- function 5

Before we begin, let's install and import PyTorch

In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros



Create a tensor filled with zeros

In [ ]:
#Example 1
torch.zeros(2)

tensor([0., 0.])

Zero filled tensor can be easily created using the torch.zeros function. If we don't pass any dtype, the type is interpreted as float by default.

Explanation about example

In [ ]:
# Example 2
torch.zeros([3,4], dtype=int)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

A list of dimensions can be passed to create a zero filled tensor with multiple dimensions. We are also setting the datatype so the zeros are integers and not floats.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.zeros([3,4], dtype=float, requires_grad=True)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64, requires_grad=True)

Only tensors which have the dtype float can have the gradients calculated. This is why, when we specify dtype as int and set the requires_gradient param to True the function breaks.


This function should be called when,
- you need a zero filled tensor
- you need to initialize a tensor whose values will be filled later on

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ayushxx7/01-tensor-operations


'https://jovian.ai/ayushxx7/01-tensor-operations'

## Function 2 - torch.sparse

Sparse matrices are those matrices where most of the elements are 0s and there are only few other values. Torch provides support for such matrices.

In [14]:
# Example 1 - working
indexTensor = torch.LongTensor([[1, 0, 1],
                                [2, 2, 3]
                               ])
valueTensor = torch.FloatTensor([7, 8, 9])
sparseTensor = torch.sparse.FloatTensor(indexTensor, valueTensor, torch.Size([4, 4])).to_dense()
print(sparseTensor)

tensor([[0., 0., 8., 0.],
        [0., 0., 7., 9.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Sparse tensor is a combination of dense tensor + index tensor (2D tensor which represents the index at which values will be placed in the sparse matrix). A size parameter is also requried, which will generate the matrix of desired size (ex: here we create a 4x4 matrix using torch.Size)

In [18]:
# Example 2 - working
indexTensorList = torch.LongTensor(([1,2], [0,2], [1, 3]))
valueTensor = torch.FloatTensor([17, 18, 19])
sparseTensor = torch.sparse.FloatTensor(indexTensorList.t(), valueTensor, torch.Size([4, 4])).to_dense()
print(sparseTensor)

tensor([[ 0.,  0., 18.,  0.],
        [ 0.,  0., 17., 19.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])


Instead of passing a 2D matrix that would populate the index, we can also create a list of indexes. In such a scenario, we would need to transpose the list using the `.t()` function.

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
indexTensorList = torch.LongTensor(([1,2], [0,2], [1, 3]))
valueTensor = torch.FloatTensor([17, 18, 19])
sparseTensor = torch.sparse.FloatTensor(indexTensorList.t(), valueTensor, torch.Size([3, 3])).to_dense()
print(sparseTensor)

RuntimeError: ignored

If the size of the matrix is less than the index provided in the indexTensor, the sparse tensor cannot be created. Hence, we need to pass at least the required dimensions as per the index tensor.

This function can be used whenever we need to create a spare matrix.

In [20]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ayushxx7/01-tensor-operations


'https://jovian.ai/ayushxx7/01-tensor-operations'

## Function 3 - torch.randn

Generating tensors filled with random values.
The special thing about this inbuilt method is that it returns a tensor filled with random numbers from a normal distribution with **mean `0` and variance `1`**

In [21]:
# Example 1 - working
torch.randn([2, 4])

tensor([[ 0.4608, -0.3125, -1.4096,  1.0789],
        [ 0.2133,  0.8766,  0.9562,  0.9583]])

We generate a tensor filled with random values by passing in the size of the tensor to the `randn` function. If we don't pass any other parameters, the dtype will be `float`

In [3]:
# Example 2 - working
torch.randn(2, 4, dtype=torch.cfloat)

tensor([[ 0.2894+0.1477j, -0.6792-0.4265j,  0.5663+0.5463j, -0.7426-0.3263j],
        [-0.5197+1.5463j,  0.2238+0.1507j,  0.0636+1.0186j,  0.4138-0.7450j]])

To create a tensor with complex numbers we can call the the `randn` function, pass in the size, and the dtype as either `torch.cfloat` or `torch.cdouble`.
One interesting thing to note is that we don't have to pass the dimensions as a list, because it accepts *size as a param.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
print(torch.rand(1, 0, 4))
torch.randn(1, 2, dtype=torch.bool)

tensor([], size=(1, 0, 4))


RuntimeError: ignored

Here, first we explore what happens we pass in 0 in the size list. The outcome is such that there are no random tensor. This is because one on the dimensions is 0, hence the tensor matrix cannot exist.
Further, we have tried to pass in the datatype as boolean, and we find out that this cannot be used in the random generator.

Whenever there is a requirement to fill a tensor with random values, especially that follows mean 0 and variance 1 rule, we can use this function. It can be used during generation of testing dataset or otherwise for experimental purposes such as while learning about what methods tensors support.

In [13]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/ayushxx7/01-tensor-operations


'https://jovian.ai/ayushxx7/01-tensor-operations'

## Function 4 - ???

Add some explanations

In [ ]:
# Example 1 - working

Explanation about example

In [ ]:
# Example 2 - working

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working

Explanation about example

In [ ]:
# Example 2 - working

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
